In [1]:
import pandas as pd
import numpy as np
import gc
import datetime
import time

%matplotlib inline

In [2]:
adData = pd.read_csv('c:\\kaggle\\adtracking\\train.csv', skiprows=range(1,175000000))
#adData = pd.read_csv('c:\\kaggle\\adtracking\\train_sample.csv')

adData.info()
adData.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9903891 entries, 0 to 9903890
Data columns (total 8 columns):
ip                 int64
app                int64
device             int64
os                 int64
channel            int64
click_time         object
attributed_time    object
is_attributed      int64
dtypes: int64(6), object(2)
memory usage: 604.5+ MB


ip  app  device  os  channel           click_time attributed_time  \
0   48212   26       1  53      121  2017-11-09 13:00:19             NaN   
1   56435   14       1  13      442  2017-11-09 13:00:19             NaN   
2  117867    9       1  19      244  2017-11-09 13:00:19             NaN   
3  111025   12       1  37      182  2017-11-09 13:00:19             NaN   
4  111025    1       1  37      101  2017-11-09 13:00:19             NaN   

   is_attributed  
0              0  
1              0  
2              0  
3              0  
4              0

In [3]:
adData['click_time'] = pd.to_datetime(adData['click_time'])
adData['click_hour'] = adData['click_time'].dt.hour
adData.drop(['click_time','attributed_time'], axis=1, inplace=True)
gc.collect()

18

In [4]:
adData.head()

ip  app  device  os  channel  is_attributed  click_hour
0   48212   26       1  53      121              0          13
1   56435   14       1  13      442              0          13
2  117867    9       1  19      244              0          13
3  111025   12       1  37      182              0          13
4  111025    1       1  37      101              0          13

In [5]:
adData.tail()

ip  app  device  os  channel  is_attributed  click_hour
9903886  121312   12       1  10      340              0          16
9903887   46894    3       1  19      211              0          16
9903888  320126    1       1  13      274              0          16
9903889  189286   12       1  37      259              0          16
9903890  106485   11       1  19      137              0          16

In [6]:
X = adData[['ip', 'app', 'device', 'os', 'channel', 'click_hour']]
y = adData['is_attributed']

In [7]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [8]:
from sklearn.linear_model import LogisticRegression

LogReg = LogisticRegression(n_jobs=-1)
LogReg.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1228: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = -1.
  " = {}.".format(self.n_jobs))


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=-1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [9]:
X_test_predict = LogReg.predict_proba(X_test)

print(X_test_predict)

[[9.99581280e-01 4.18719570e-04]
 [9.99385753e-01 6.14246876e-04]
 [9.98208796e-01 1.79120441e-03]
 ...
 [9.97442113e-01 2.55788706e-03]
 [9.97797563e-01 2.20243737e-03]
 [9.99862593e-01 1.37407455e-04]]


In [10]:
adTest = pd.read_csv('c:\\kaggle\\adtracking\\test.csv')

In [11]:
adTest.info()
adTest.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18790469 entries, 0 to 18790468
Data columns (total 7 columns):
click_id      int64
ip            int64
app           int64
device        int64
os            int64
channel       int64
click_time    object
dtypes: int64(6), object(1)
memory usage: 1003.5+ MB


click_id      ip  app  device  os  channel           click_time
0         0    5744    9       1   3      107  2017-11-10 04:00:00
1         1  119901    9       1   3      466  2017-11-10 04:00:00
2         2   72287   21       1  19      128  2017-11-10 04:00:00
3         3   78477   15       1  13      111  2017-11-10 04:00:00
4         4  123080   12       1  13      328  2017-11-10 04:00:00

In [12]:
adTest.tail()

click_id      ip  app  device  os  channel           click_time
18790464  18790464   99442    9       1  13      127  2017-11-10 15:00:00
18790465  18790465   88046   23       1  37      153  2017-11-10 15:00:00
18790466  18790467   81398   18       1  17      265  2017-11-10 15:00:00
18790467  18790466  123236   27       1  13      122  2017-11-10 15:00:00
18790468  18790468   73516   12       2  27      265  2017-11-10 15:00:00

In [13]:
adTest['click_time'] = pd.to_datetime(adTest['click_time'])
adTest['click_hour'] = adTest['click_time'].dt.hour
adTest.drop(['click_time'], axis=1, inplace=True)
gc.collect()

34

In [14]:
ad_test = adTest[['ip', 'app', 'device', 'os', 'channel', 'click_hour']]
ad_test_predict = LogReg.predict_proba(ad_test)

print(ad_test_predict)

[[9.03554126e-01 9.64458741e-02]
 [9.08147587e-01 9.18524126e-02]
 [8.05645866e-01 1.94354134e-01]
 ...
 [9.99459606e-01 5.40393536e-04]
 [9.98246907e-01 1.75309262e-03]
 [9.99585769e-01 4.14230578e-04]]


In [15]:
print(ad_test_predict[::, 1])

[0.09644587 0.09185241 0.19435413 ... 0.00054039 0.00175309 0.00041423]


In [16]:
submit_file = 'c:\\kaggle\\adtracking\\Submission_logreg.csv'
print(submit_file)
submission = pd.DataFrame({
        "click_id": adTest["click_id"],
        "is_attributed": ad_test_predict[::, 1]
    })

submission.to_csv(submit_file, index=False)

c:\kaggle\adtracking\Submission_logreg.csv
