In [17]:
import numpy as np

# array operation
ar1 = np.array([1, 2, 3])
ar2 = np.array([4, 5, 6])

print ar1
print ar2

ar3 = ar1 + ar2
print ar3
# ar3 is a (1 x 3) matrix

ar4 = ar3.reshape([3, 1])

print ar4

t_ar3 = ar3.transpose()
print t_ar3
print np.dot(ar3, t_ar3)

ar5 = np.array([[1,2,3],[4,5,6]])
print ar5 + ar5

ar6 = np.array([[1,-3,4], [2,10,-7], [0,1,0], [0,0,0]])
ar7 = np.array([[5,0], [-2,11], [-3,12]])

print np.dot(ar6, ar7)

[1 2 3]
[4 5 6]
[5 7 9]
[[5]
 [7]
 [9]]
[5 7 9]
155
[[ 2  4  6]
 [ 8 10 12]]
[[-1 15]
 [11 26]
 [-2 11]
 [ 0  0]]


In [24]:
mt_W = np.array([[1,2,3], [3,2,1]])
mt_X = np.array([[1,0], [2,-1], [0,2]])
mt_Y = np.array([[0,1], [-2,5]])

print np.dot(mt_W, mt_X) + mt_Y
print np.dot(mt_X, mt_Y)
print np.dot(np.dot(mt_W, mt_X), mt_Y)

[[5 5]
 [5 5]]
[[ 0  1]
 [ 2 -3]
 [-4 10]]
[[-8 25]
 [ 0  7]]


In [34]:
mt_W = np.array([[1,-3],[2,-2],[3,1]])
mt_X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
mt_Y = np.array([[1,2,0],[0,-1,2]])
mt_Z = np.array([[0,1],[2,3]])

print np.dot(mt_Y, mt_W) - mt_Z
print np.dot(mt_W, mt_Y) - mt_X
print np.dot(mt_Y, mt_W) - np.square(mt_Z)

[[ 5 -8]
 [ 2  1]]
[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]
[[ 5 -8]
 [ 0 -5]]
